# Generated by Django 2.2.5 on 2019-12-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('sender_user_name', models.CharField(max_length=255)),
                ('receiver_user_id', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('sent_date', models.DateField()),
                ('received_date', models.DateField()),
                ('read_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('delete_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('sender_user_id', models.CharField(max_length=255)),
            ],
        ),
    ]
