# Generated by Django 2.2.5 on 2019-12-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='read_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='received_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sent_date',
            field=models.DateTimeField(),
        ),
    ]
